on:
  push:
    branches:
      - master

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

name: Build and publish documentation to GitHub Pages

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  publish:
    name: Build and publish documentation
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Create input files for doxygen
      run: ./doxygenHTML.sh

    - name: Build doxygen
      uses: mattnotmitt/doxygen-action@1.8.18
      with:
        working-directory: docs
        doxyfile-path: ogit-doxyfile

    # Necessary because the action above runs as root
    # and therefore creates all its files with root:root owner.
    - name: Copy output files so that their directory is writable
      run: cp -r docs/html _site

    - name: Overwrite with custom styling files
      run: cp docs/doxygen/* _site

    - name: Upload github-pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: _site

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
